fund/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include('main.urls')),
    path("admin/", admin.site.urls),
]

main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from . import api

app_name="main"
urlpatterns = [
    # Authentication
    path('', views.index, name="index"),
    path('register/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('account/', views.account_details, name="account_details"),
    path('account/changepassword/', views.change_password, name="changepassword"),
    

    # Member Dashboard and Actions
    path('member/', views.member_dashboard, name='member_dashboard'),
    path('member/update-profile/', views.update_member_profile, name='update_member_profile'),
    path('member/payment-history/', views.member_payment_history, name='member_payment_history'),
    path('member/claim/create/', views.create_claim, name='create_claim'),
    path('member/claim/list/', views.claims_list, name='claim_list'),
    path('member/claim/update/<int:claim_id>', views.update_claim, name='update_claim'),

    path('member/beneficiary/list/', views.beneficiary_list, name='beneficiary_list'),
    path('member/beneficiary/add/', views.add_beneficiary, name='add_beneficiary'),
    path('member/beneficiary/update/<int:beneficiary_id>/', views.update_beneficiary, name='update_beneficiary'),
    path('member/beneficiary/delete/<int:beneficiary_id>/', views.delete_beneficiary, name='delete_beneficiary'),
    

    # Trustee Dashboard and Actions
    path('trustee/', views.trustee_dashboard, name='trustee_dashboard'),
    path('trustee/analytics/', views.trustee_analytics, name='trustee_analytics'),

    path('trustee/create/<int:member_id>/', views.create_trustee, name='create_trustee'),
    path('trustee/update/<int:trustee_id>/', views.update_trustee, name='update_trustee'),
    path('trustee/delete/<int:trustee_id>/', views.delete_trustee, name='delete_trustee'),

    path('trustee/claim/list/', views.trustee_claim_list, name='trustee_claim_list'),
    path('trustee/claim/<int:claim_id>/', views.claiminfo, name='claim_info'),
    path('trustee/claim/approve/<int:claim_id>/', views.approve_claim, name='approve_claim'),
    path('trustee/claim/reject/<int:claim_id>/', views.reject_claim, name='reject_claim'),
    path('trustee/settings/', views.trustee_settings, name="trustee_settings"),

    #path('trustee/beneficiary/<int:beneficiary_id>', views.beneficiaryinfo, name='beneficiary_info'),
    
    path('trustee/member/list/', views.member_list, name='member_list'),
    #path('trustee/member/update-payment/<int:member_id>/', views.update_payment_status, name='update_payment'),
    path('trustee/member/add-payment/<int:member_id>/', views.add_payment, name="add_payment"),
    path('trustee/member/info/<int:member_id>/', views.member_info, name='member_info'),
    path('trustee/member/delete/<int:member_id>/', views.member_delete, name='delete_member'),


    # ANALYTICS API
    path("api/trends/", api.trends_view, name='trends_api'),
    path("download/claims/", api.claims_export, name="claims_download"),
    path("download/beneficiaries/", api.beneficiaries_export, name="beneficiaries_download"),
    path("download/members/", api.members_export, name="members_download"),
    path("download/contributions/", api.contributions_export, name="contributions_download"),

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

main/forms.py
from django import forms
from datetime import date
from .models import Member, Claim, Beneficiary, CustomUser, Trustee, Setting

class MemberForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ['email', 'first_name', 'last_name', 'password']

    def save(self, commit=True):
        user = super(MemberForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
            # Create the associated member profile
            Member.objects.create(user=user, membership_date = date.today())
        return user


class AccountForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['email', 'first_name', 'last_name']
        
    def save(self, commit=True):
        user = super(AccountForm, self).save(commit=False)
        #user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user


class MemberDetailForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ['phone_number', 'gender', 'date_of_birth', 'id_number', 'hit_ec_number', 'residential_address', 'employment_position', 'extension', 'fax', 'department', 'employment_duration', 'office_number']
        widgets = {
            'residential_address': forms.Textarea(attrs={'rows': 2}),
            'date_of_birth': forms.DateInput(attrs={'type': 'date'}),
            'gender': forms.Select(choices=[('male', 'Male'), ('female', 'Female')]),
        }

class TrusteeForm(forms.ModelForm):
    class Meta:
        model = Trustee
        fields = ['position', 'role', 'description']

class SettingsForm(forms.ModelForm):
    class Meta:
        model = Setting
        exclude = []


class ClaimForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.qset = kwargs.pop("qset", None)
        super(ClaimForm, self).__init__(*args, **kwargs)
        if self.qset:
            self.fields['beneficiary'].queryset = self.qset

    class Meta:
        model = Claim
        fields = ['beneficiary', 'description', 'proof_of_claim']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 2}),
        }


class BeneficiaryForm(forms.ModelForm):
    class Meta:
        model = Beneficiary
        fields = ['full_name', 'relationship_type', 'id_number', 'proof_of_relationship']
        widgets = {
            'relationship_type': forms.Select(choices=[('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('principal', 'Principal'), ('nominee', 'Nominee')]),
        }


class LoginForm(forms.Form):
    email = forms.EmailField(max_length=255, required=False)
    password = forms.CharField(widget=forms.PasswordInput)


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput, required=True)
    new_password = forms.CharField(widget=forms.PasswordInput, required=True)


main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.contrib import messages
from django.db.models import Q
from datetime import datetime, timedelta
from .models import Member, Trustee, Beneficiary, Claim, PaymentHistory, EventLog, CustomUser, Setting
from .forms import MemberForm, ClaimForm, BeneficiaryForm, LoginForm, MemberDetailForm, TrusteeForm, ChangePasswordForm, AccountForm, SettingsForm

@login_required
def index(request):
    if hasattr(request.user, 'trustee'):
        return redirect("main:trustee_dashboard")
    if hasattr(request.user, 'member'):
        return redirect("main:member_dashboard")
    return redirect("main:signup")


def signup_view(request):
    if request.method == 'POST':
        form = MemberForm(request.POST)
        if form.is_valid():
            user = form.save()
            # Create a member profile linked to the user
            # Member.objects.create(user=user)
            login(request, user)
            messages.info(request, "Let's finish setting up your account. ")
            return redirect('main:update_member_profile')
        else:
            messages.error(request, "You submitted invalid information, please check for errors. ")
            return render(request, 'signup.html', {'form': form})
    else:
        form = MemberForm()
        return render(request, 'signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "Welcome back!")
                if hasattr(user, 'Trustee'):
                    return redirect('main:trustee_dashboard')
                elif hasattr(user, 'member'):
                    return redirect('main:member_dashboard')
            else:
                messages.error(request, 'Invalid email or password')
                return render(request, 'login.html', {'form': form})
    else:
        form = LoginForm()
        return render(request, 'login.html', {'form': form})


@login_required
def change_password(request):
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            old_password = form.cleaned_data['old_password']
            new_password = form.cleaned_data['new_password']
            if request.user.check_password(old_password):
                myuser = CustomUser.objects.get(email=request.user.email)
                myuser.set_password(new_password)
                myuser.save()
                logout(request)
                messages.success(request, "The user's password was changed successfully. ")
                return redirect("main:login")
            else:
                messages.error(request, "The old password you entered is incorrect!")
                return render(request, 'form.html', {'form': form, 'title' : 'Change Password'})
        else:
            messages.error(request, "The passwords you entered are invalid!")
            return render(request, 'form.html', {'form': form, 'title' : 'Change Password'})
    else:
        form = ChangePasswordForm()
        return render(request, 'form.html', {'form': form, 'title' : 'Change Password'})


@login_required
def account_details(request):
    if request.method == "POST":
        form = AccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            logout(request)
            messages.success(request, "The user's details were changed successfully. ")
            return redirect("main:login")
        else:
            messages.error(request, "The information you entered is invalid!")
            return render(request, 'form.html', {'form': form, 'title' : 'Account Settings'})
    else:
        form = AccountForm(instance=request.user)
        return render(request, 'form.html', {'form': form, 'title' : 'Account Settings'})


@login_required
def logout_view(request):
    logout(request)
    return redirect('main:login')


@login_required
def update_member_profile(request):
    member = request.user.member  # Retrieve the member associated with the logged-in user
    if request.method == 'POST':
        form = MemberDetailForm(request.POST, instance=member)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile updated successfully!')
            return redirect('main:member_dashboard')
        else:
            messages.error(request, "You submitted invalid information, please check for errors. ")
            return render(request, 'member-form.html', {'form': form})
    else:
        form = MemberDetailForm(instance=member)
        return render(request, 'member-form.html', {'form': form, 'title' : "Update member Details", 'subtitle' : member.user})


@login_required
def member_dashboard(request):
    if not hasattr(request.user, 'member'):
        return HttpResponse('Unauthorized', status=401)
    member = request.user.member
    history = PaymentHistory.objects.filter(member=member).order_by("-payment_date")[:3]
    beneficiaries = member.beneficiaries.all()
    return render(request, 'member_dashboard.html', {'member': member, 'rclaims': Claim.objects.filter(member=member, status = "rejected"), 'aclaims': Claim.objects.filter(member=member, status = "approved"), 'beneficiaries': beneficiaries, 'history' : history, "title" : f'Welcome {request.user.member}'})


@login_required
def member_info(request, member_id):
    if not hasattr(request.user, 'trustee'):
        return HttpResponse('Unauthorized', status=401)
    member = get_object_or_404(Member, id=member_id)
    claims = Claim.objects.filter(member=member)
    beneficiaries = member.beneficiaries.all()
    istrustee = Trustee.objects.filter(user = member.user).exists()
    mtrustee = None
    if istrustee:
        mtrustee = Trustee.objects.get(user = member.user)
    print(PaymentHistory.objects.filter(member=member, period = datetime(datetime.today().year, datetime.today().month, 1)))
    fpaid = PaymentHistory.objects.filter(member=member, period__year = datetime.today().year, period__month = datetime.today().month).exists()
    return render(request, 'member_details.html', {'member': member, 'claims': claims, 'beneficiaries': beneficiaries, 'trustee' : mtrustee, "title" : "Member Details", "fullypaid" : fpaid})


@login_required
def member_list(request):
    if not hasattr(request.user, 'trustee'):
        return HttpResponse('Unauthorized', status=401)

    memberslist = Member.objects.all()

    if 'query' in request.GET:
        query = request.GET['query']
        memberslist = Member.objects.filter(
                Q(user__first_name__icontains=query) | 
                Q(user__last_name__icontains=query) | 
                Q(user__email__icontains=query) | 
                Q(hit_ec_number=query) |
                Q(id_number=query)  # Assuming `id` represents the ID number for the member
            )
    return render(request, 'member_list.html', {"members" : memberslist, "title" : "Members List"})

@login_required
def member_delete(request, member_id):
    if not hasattr(request.user, 'trustee'):
        return HttpResponse('Unauthorized', status=401)
    oldmember = Member.objects.get(id = member_id)
    
    EventLog.objects.create(event = f'Deleted Trustee ({oldmember.user.first_name + oldmember.user.last_name})', event_type = "delete", trustee = Trustee.objects.get(user = request.user))
    # oldmember.delete()
    CustomUser.objects.get(email = Member.objects.get(id = member_id).user.email).delete()
    messages.success(request, "The member was successfully deleted!")
    return redirect("main:member_list")


@login_required
def trustee_dashboard(request):
    if not hasattr(request.user, 'trustee'):
        return HttpResponse('Unauthorized', status=401)
    claims = Claim.objects.filter(status='pending')  # List pending claims

    ## Setting the Settings if they don't exists --->
    if Setting.objects.all().first() == None:
        Setting.objects.create(
            monthly_contribution = 2
        )
    
    return render(request, 'trustee_dashboard.html', {
        'pending_claims': claims,
        "members_count" : Member.objects.all().count(),
        'trustees_count' : Trustee.objects.all().count(),
        'beneficiaries_count' : Beneficiary.objects.all().count(),
        'claims_count' : Claim.objects.all().count(),
        'events' : EventLog.objects.order_by("-event_date")[:20],
        "title" : "Trustee Dashboard"
    })


@login_required
def trustee_analytics(request):
    if not hasattr(request.user, 'trustee'):
        return HttpResponse('Unauthorized', status=401)
    
    return render(request, 'trustee_analytics.html', {
        "title" : "Trustee Dashboard"
    })

@login_required
def create_trustee(request, member_id):
    if not hasattr(request.user, 'trustee'):
        return HttpResponse('Unauthorized', status=401)
    if request.method == "POST":
        form = TrusteeForm(request.POST)
        if form.is_valid():
            newtrustee = form.save(commit=False)
            newtrustee.user = Member.objects.get(id=member_id).user
            newtrustee.save()

main/templates/add_beneficiary.html
{% extends 'base.html' %}
{% block content %}
<h1>Add a Beneficiary</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Beneficiary</button>
</form>
{% endblock %}

main/templates/claim_detail.html
{% extends 'trustee-base.html' %}
{% block content %}

<div class="main grid grid-cols-1 gap-10 md:gap-16 max-h-[90vh] overflow-y-auto">

            

    <div class="text-[0.7rem] md:text-[0.9rem] md:mr-6 *:bg-white *:rounded-md flex flex-col gap-3">

        <div class="py-5 px-7 pb-4">
            <h2>Claim from {{ claim.member.user }}</h2>

            <p class="tags py-3 flex flex-row gap-2 *:rounded-2xl *:px-3 *:py-1 *:bg-blue-50 *:cursor-pointer">
                {% if claim.status == "rejected" %}
                <span class="tag !bg-red-50">
                    <i class="bi bi-x text-red-500 mr-1"></i> Rejected
                </span>
                {% elif claim.status == "pending" %}
                <span class="tag !bg-gray-50">
                    <i class="bi bi-clock text-gray-500 mr-1"></i> Pending...
                </span>
                {% elif claim.status == "approved" %}
                <span class="tag">
                    <i class="bi bi-patch-check-fill text-blue-500"></i> Approved
                </span>
                {%endif%}
                
            </p>
        </div>

        {% if claim.status == "pending" and claim.member.user != request.user %}
        <form class="py-5 px-7 pb-4 flex flex-row items-center gap-3" action="{% url 'main:approve_claim' claim.pk %}" method="post">
            {% csrf_token %}
            <span>USD</span>
            <input class="h-fit" value="{{ amount }}" min="0" readonly="True" max="99999999" placeholder="Amount" type="number" name="amount">
            <button type="submit">Approve</button>
            <span>|</span>
            <a class="btn text-red-500 !px-6 !border-red-500" href="{% url 'main:reject_claim' claim.pk %}" type="button">Reject</a>
        </form>
        {% endif %}
        

        <div class="py-9 px-7">

            <h3 class="mb-4 font-bold text-xl text-blue-950">Infomation</h3>

            <div class="grid grid-cols-1 md:grid-cols-3 gap-5 *:flex *:flex-col even:*:*:font-bold">
            
                <div>
                    <span>Beneficiary Fullname</span>
                    <span>{{ claim.beneficiary.full_name }}</span>
                </div>

                <div>
                    <span>Beneficiary ID</span>
                    <span>{{ claim.beneficiary.id_number }}</span>
                </div>

                <div>
                    <span>Beneficiary Relationship</span>
                    <span>{{ claim.beneficiary.relationship_type }}</span>
                </div>

                <div>
                    <span>Date Filed</span>
                    <span>{{ claim.date_filed }}</span>
                </div>

                {% if claim.status == "approved" %}
                <div>
                    <span>Approval Date</span>
                    <span>{{ claim.approval_date }}</span>
                </div>

                <div>
                    <span>Approved By</span>
                    <span>{{ claim.approved_by.user }}</span>
                </div>

                <div>
                    <span>Amount Claimed</span>
                    <span>{{ claim.amount_claimed }} USD</span>
                </div>

                
                {% endif %}

                <div>
                    <span>Proof</span>
                    <span><a href="{{ claim.proof_of_claim.url }}">Download</a></span>
                </div>

                <div>
                    <span>Description</span>
                    <span>{{ claim.description }}</span>
                </div>


            </div>


        </div>




    </div>

    

</div>

{% endblock %}

main/templates/member_beneficiary_table.html
{% extends 'member-base.html' %}
{% block content %}


<div class="main grid grid-cols-1 gap-2 md:gap-12 max-h-[90vh] overflow-y-auto">

            
    <div class="w-full overflow-x-auto bg-white py-7 px-6">
        <a href="{% url 'main:add_beneficiary' %}" class="btn">Add Beneficiary</a>
        <div class="grid grid-cols-[auto,auto,auto,auto,auto] *:p-4 w-full *:border-b-2">

            <span class="font-bold !border-b-[3px] !border-black">
                #
            </span>
            <span class="font-bold !border-b-[3px] !border-black">
                Fullname
            </span>
            <span class="font-bold !border-b-[3px] !border-black">
                Relationship
            </span>
            <span class="font-bold !border-b-[3px] !border-black">
                ID Number
            </span>
            <span class="font-bold !border-b-[3px] !border-black">
                Proof
            </span>


            {% for beneficiary in beneficiaries %}

                <span class="flex flex-row gap-3">
                    {% if beneficiary.claim %}
                    -
                    {% else %}
                    <a class="btn text-red-500 !my-0 h-fit" href="{% url 'main:delete_beneficiary' beneficiary.pk %}">
                        <i class="bi bi-trash text-sm"></i>
                    </a>
                    <a class="btn !my-0 h-fit" href="{% url 'main:update_beneficiary' beneficiary.pk %}">
                        <i class="bi bi-pencil text-sm"></i>
                    </a>
                    {% endif %}
                    
                </span>
                <span>
                    {{beneficiary.full_name}}
                </span>
                <span>
                    {{beneficiary.relationship_type}}
                </span>
                <span>
                    {{beneficiary.id_number}}
                </span>
                <span>
                    <a href="{{ beneficiary.proof_of_relationship.url }}">Download</a>
                </span>

            {% endfor %}

            
        </div>
    </div>
    

</div>

{% endblock %}

main/templates/member_details.html
{% extends 'trustee-base.html' %}
{% block content %}

<div class="main grid grid-cols-1 gap-10 md:gap-16 max-h-[90vh] overflow-y-auto">

    <div class="text-[0.7rem] md:text-[0.9rem] md:mr-6 *:bg-white *:rounded-md flex flex-col gap-3">

        <div class="py-5 px-7 pb-4">
            <h2>
                {{ member.user }}
                {% if member.user == request.user %}
                (You)
                {% endif %}
            </h2>

            <p class="tags py-3 flex flex-row gap-2 *:rounded-2xl *:px-3 *:py-1 *:bg-blue-50 *:cursor-pointer">
                {% if trustee %}
                <span class="tag">
                    <i class="bi bi-patch-check-fill text-blue-500"></i> Trustee
                </span>
                {% endif %}

                {% if fullypaid %}
                <span class="tag">
                    <i class="bi bi-cash-stack text-blue-500 mr-1"></i> Fully Paid
                </span>
                {% else %}
                <span class="tag !bg-red-50">
                    <i class="bi bi-cash-stack text-red-500 mr-1"></i> Not Paid
                </span>
                {% endif %}
            </p>
        </div>

        <div class="py-5 px-7 pb-4 flex flex-row gap-3 flex-wrap">
            {% if request.user.trustee != trustee %}
            <a class="btn" href="{% url 'main:add_payment' member.pk %}">Add Payment</a>
            <a class="btn" href="{% url 'main:delete_member' member.pk %}">Delete Member</a>

            {% if trustee %}
            <a class="btn" href="{% url 'main:update_trustee' trustee.pk %}">Edit Trustee</a>
            <a class="btn" href="{% url 'main:delete_trustee' trustee.pk %}">Delete Trustee</a>
            {% else %}
            <a class="btn" href="{% url 'main:create_trustee' member.pk %}">Make Trustee</a>
            {% endif %}
            
            {% endif %}
            
            <a class="btn" href="mailto:{{member.user.email}}">Email Now!</a>
        </div>
        

        <div class="py-9 px-7">

            <h3 class="mb-4 font-bold text-xl text-blue-950">Infomation</h3>

            <div class="grid grid-cols-1 md:grid-cols-3 gap-5 *:flex *:flex-col even:*:*:font-bold">
            
                <div>
                    <span>Email Address</span>
                    <span>{{member.user.email}}</span>
                </div>

                <div>
                    <span>Phone Number</span>
                    <span>{{ member.phone_number }}</span>
                </div>

                <div>
                    <span>Extension</span>
                    <span>{{ member.extension }}</span>
                </div>

                <div>
                    <span>Fax</span>
                    <span>{{ member.fax }}</span>
                </div>

                <div>
                    <span>Date Of Birth</span>
                    <span>{{ member.date_of_birth }}</span>
                </div>

                <div>
                    <span>ID Number</span>
                    <span>{{ member.id_number }}</span>
                </div>

                <div>
                    <span>HIT EC Number</span>
                    <span>{{ member.hit_ec_number }}</span>
                </div>

                <div>
                    <span>Residential Address</span>
                    <span>{{ member.residential_address }}</span>
                </div>

                <div>
                    <span>Employment Position</span>
                    <span>{{ member.employment_position }}</span>
                </div>

                <div>
                    <span>Department</span>
                    <span>{{ member.department }}</span>
                </div>

                <div>
                    <span>Office Number</span>
                    <span>{{member.office_number}}</span>
                </div>

                <div>
                    <span>Employment Duration</span>
                    <span>{{ member.employment_duration }}</span>
                </div>

            </div>


        </div>



        {% if trustee %}
        <div class="py-9 px-7">
            <h3 class="mb-4 font-bold text-xl text-blue-950">Trustee Details</h3>

            <div class="grid grid-cols-1 md:grid-cols-3 gap-5 *:flex *:flex-col even:*:*:font-bold">
            
                <div>
                    <span>Position</span>
                    <span>{{trustee.position}}</span>
                </div>

                <div>
                    <span>Role</span>
                    <span>{{ trustee.role }}</span>
                </div>

                <div>
                    <span>Description</span>
                    <span>{{ trustee.description }}</span>
                </div>

            </div>
        </div>
        {% endif %}



        <div class="py-9 px-7">
            <h3 class="mb-4 font-bold text-xl text-blue-950">Beneficiaries</h3>
            <div class="w-full overflow-x-auto">
                <div class="grid grid-cols-[auto,auto,auto,auto] *:p-4 w-full *:border">

                    <span class="font-bold !border-b-2">
                        Fullname
                    </span>
                    <span class="font-bold !border-b-2">
                        Relationship
                    </span>
                    <span class="font-bold !border-b-2">
                        ID Number
                    </span>
                    <span class="font-bold !border-b-2">
                        Proof
                    </span>

                    {% for beneficiary in beneficiaries %}
                        <span>
                            {{beneficiary.full_name}}
                        </span>
                        <span>
                            {{beneficiary.relationship_type}}
                        </span>
                        <span>
                            {{beneficiary.id_number}}
                        </span>
                        <span>
                            <a href="{{beneficiary.proof_of_relationship.url}}">Download</a>
                        </span>
                    {% endfor %}

                </div>
            </div>
            


        </div>


        <div class="py-9 px-7">
            <h3 class="mb-4 font-bold text-xl text-blue-950">Claims</h3>
            <div class="w-full overflow-x-auto">
                <div class="grid grid-cols-[auto,auto,auto,auto] *:p-4 w-full *:border">

                    <span class="font-bold !border-b-2">
                        Beneficiary Fullname
                    </span>
                    <span class="font-bold !border-b-2">
                        Relationship
                    </span>
                    <span class="font-bold !border-b-2">
                        Date Filed
                    </span>
                    <span class="font-bold !border-b-2">
                        Status
                    </span>


                    {% for claim in claims %}

                    <span>
                        <a href="{% url 'main:claim_info' claim.pk %}">⇗</a>
                        {{claim.beneficiary.full_name}}
                    </span>
                    <span>
                        {{ claim.beneficiary.relationship_type }}
                    </span>
                    <span>
                        {{ claim.beneficiary.id_number }}
                    </span>

                    {% if claim.status == "pending" %}
                    <span class="">
                        Pending...
                    </span>
                    {% elif claim.status == "approved" %}
                    <span class="text-primary">
                        Approved
                    </span>
                    {% elif claim.status == "rejected" %}
                    <span class="text-red-500">
                        Rejected
                    </span>
                    {%endif%}

                    {% endfor %}


                </div>
            </div>
            


        </div>


    </div>

    <div class="">
        
    </div>
    

</div>

{% endblock %}